@startuml Алгоритм_изменения_проекта
start
rectangle TimeNoteView {
:пользователь нажимает на кнопку проекта;
}
rectangle OpenProjectFormCommand {
    :создание ProjectForm с текущим проектом;
    :привязка ProjectFrom к TimeNoteVM;
}
rectangle TimaNoteVM {
    :привязка к событию ProjectFrom.Closed;
}

rectangle OpenProjectFormCommand {
    :навигация ProjectFrom в ModalVM;
}
:открытие окна ProjectFrom;
rectangle ProjectFormVM {
    :State = не выбран;
    while (пользователь закрыл форму?) is (нет)
        if(пользователь выбирает существующий проект) then (да)
            :CurrentProject = выбранный проект;
            :State = выбран;
        else (нет)
            if (пользователь ввел имя проекта и нажал на кнопку создать) then (да)
                :валидация ввода;
                if (ввод корректный) then (да)
                :создание нового проекта;
                :CurrentProject = созданный проект;   
                :State = выбран;
                else (нет)
                    :сообщение на форме;
                endif
            endif 
        endif

        if (новый проект выбран?) then (да)
            :назначение нового проекта проекта;
            :закрытие формы;
        endif
    endwhile (да)
}
rectangle TimaNoteVM { 
    if (State == Выбран) then (да)
        :назначение нового проекта;
    endif
}
end
@enduml