@startuml

class "ServiceProvider" as sp

class MainWindow
class MainViewModel

MainViewModel --o MainWindow

sp ..> MainWindow

rectangle ViewModels{
    class TimerViewModel
    class NoteListingViewModel
    class TimerLayoutViewModel

    sp ..> TimerViewModel
    sp ..> NoteListingViewModel
    sp ..> TimerLayoutViewModel
}

rectangle Stores{
    class ModalStore
    class NavigationStore
    class TodayDateStore

    sp ..> ModalStore
    sp ..> NavigationStore
    sp ..> TodayDateStore
}

rectangle Services{
    class OpenModalNavigationService
    class CloseModalNavigationService

    sp ..> OpenModalNavigationService
    sp ..> CloseModalNavigationService
}

rectangle Validators{
    class NoteValidator

    sp ..> NoteValidator
}

rectangle Repository{
    class TimaNoteRepository

    sp ..> TimaNoteRepository
}

rectangle Factories{
    entity "Func<Type, ViewModelBase>" as func
    class NoteFactory

    sp ..> func
    sp ..> NoteFactory
}



@enduml