@startuml

class "ProjectFormViewModel" as pf {
    - _projectRepository
    + CurrentProject
    + Projects

    + AddingProjectEdit
    + AddProjectCommand
    + AddProject()
}

class "ProjectViewModelBase" as projectBase{
    - _validator
    + Name

}

class "ProjectViewModel" as projectVM {
    - _project
    - _projectRepository
    + IsEmpty
    + ProjectEdit
    + DeleteProject()
}

pf "1" --> "*" projectVM

class "ProjectEditViewModel" as projectEdit{

}

projectEdit --|> projectBase
projectVM --|> projectBase

projectEdit --o pf
projectEdit --o projectVM


interface "ProjectRepository" as pr {
    + Contains(string)
    + Contains(Project)
    + GetId()
    + AddProject(Project)
    + UpdateProject(Project)
    + RemoveProject(Project)
    + GetProjects()

}

pf --> pr
projectVM --> pr


@enduml