class "ProjectViewModel" as projectVM {
    - _project
    + IsEmpty
    + Name
    + Id
}

class "EditableProjectViewModel" as editableProjectVM {
    - _validator
    - _projectRepository
    + DeleteProject()
    + UpdateProject()
}

editableProjectVM -o projectVM :"extends"