@startuml

class TimerLayout
class Timer
class ListingNote
class NoteItem
class EditableNote
class Note 



ListingNote --o TimerLayout
Timer --o TimerLayout
EditableNote --|> Note

Timer --|> EditableNote
NoteItem --|> EditableNote
ListingNote ..> NoteItem


@enduml