@startuml timaproject-use-case

left to right direction

actor Пользователь as user

(изменение record из таймера) as changeRecordTimer
(запуск таймера) as startTimer

(создание record) as changeRecord



user -- changeRecordTimer

user -- startTimer

startTimer ..> changeRecord

changeRecordTimer ..> (изменение заголовка) 
changeRecordTimer ..> (изменение StartTime)
changeRecordTimer ..> (изменение проекта)

user -- (остановка таймера)

(остановка таймера) ..> (запись EndTime в record)


user -- (удаление record)
user -- (создание record без таймера)
user -- (изменение record из списка)
(изменение record из списка) ..> (изменение заголовка) 
(изменение record из списка) ..> (изменение проекта)
(изменение record из списка) ..> (изменение времени record)
(изменение времени record) ..> (изменение StartTime)
(изменение времени record) ..> (изменение EndTime)
(изменение времени record) ..> (изменение свойства Time)
(изменение record из списка) ..> (добавление заметок к завершенным записям)


@enduml