@startuml timaproject-use-case

actor Пользователь as user

(Запустить таймер) as startTimer
(Сохранить record) as saveRecord
(Изменить Record) as changeRecord
(Изменить Title) as changeTitle

(Изменить время) as changeTime
(Изменить endtime) as setEndTime
(Изменить date) as setDate
(Изменить starttime) as setStartTime
changeTime -- setEndTime : "если record завершенная"
changeTime -- setDate
changeTime -- setStartTime
setEndTime -- saveRecord
setStartTime -- saveRecord
setDate -- saveRecord
changeTitle -- saveRecord

(Настроить проект) as handleProject
(Назначить проект) as setProject
(Добавить новый проект) as addProject
handleProject -- addProject
handleProject -- setProject
addProject -- setProject
setProject -- saveRecord

(Настраивать заметки) as handleNote
(Добавить заметку) as addNote
(Удалить заметку) as removeNote
(Изменить заметку) as changeNote
handleNote -- addNote
handleNote -- removeNote
handleNote -- changeNote

changeRecord -- changeTitle
changeRecord -- handleProject
changeRecord -- changeTime
changeRecord -- handleNote

(Остановка таймера) as stopTimer

(Удалить проект) as removeProject
(Изменить проект)  as changeProject

user -- changeProject
user -- removeProject

user -- startTimer

startTimer -- (Добавить record)
startTimer -- (Начать отсчет)

user -- changeRecord 
user -- stopTimer

stopTimer -- setEndTime
stopTimer -- (Обнулить timer и записи таймера)

user -- (Удалить record)
user -- (Добавить record)


@enduml